"""Initial migration

Revision ID: 9e8d0fc24179
Revises: 
Create Date: 2025-10-13 23:47:32.834324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e8d0fc24179'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_no', sa.String(length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('class_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('uq_students_reg_no'))
        batch_op.create_unique_constraint(None, ['admission_no'])
        batch_op.drop_column('reg_no')
        batch_op.drop_column('phone')
        batch_op.drop_column('total_fee')
        batch_op.drop_column('created_at')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('total_fee', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('reg_no', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_students_reg_no'), ['reg_no'], unique=True)
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('class_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('admission_no')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), nullable=True))
        batch_op.drop_column('reference')
        batch_op.drop_column('method')
        batch_op.drop_column('payment_date')

    # ### end Alembic commands ###
